import { useState } from "react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Mermaid } from "./mermaid";
import { CodeBlock } from "./code-block";
import { ArchitectureCanvas, useArchitectureGraph } from "./studio/architecture-canvas";
import { Button } from "@/components/ui/button";
import { Download, PenLine, GitBranch } from "lucide-react";

interface ArchitectureData {
  id?: number;
  title?: string;
  diagram?: string;
  terraform?: string;
  costEstimate?: string;
  securityRecommendations?: string;
  highAvailabilityPlan?: string;
  databaseRecommendation?: string;
  kubernetesDeployment?: string;
  cicdPipeline?: string;
  monitoringSetup?: string;
  disasterRecovery?: string;
}

interface ArchitectureViewerProps {
  architecture: ArchitectureData;
  isDetail?: boolean;
}

function TextSection({ value, emptyLabel }: { value?: string; emptyLabel: string }) {
  if (!value || !value.trim()) {
    return <p className="text-sm text-muted-foreground">{emptyLabel}</p>;
  }
  return <div className="whitespace-pre-wrap font-mono text-sm leading-relaxed">{value}</div>;
}

/**
 * The diagram tab offers two views of the same design: an interactive Studio
 * (drag, connect, and cost/tradeoff insights) and the AI's original blueprint.
 */
function DiagramTab({ diagram }: { diagram?: string }) {
  const [view, setView] = useState<"studio" | "blueprint">("studio");
  // Own the graph here so edits survive switching between Studio and Blueprint.
  const graph = useArchitectureGraph(diagram);

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h3 className="text-base font-semibold text-foreground">
            {view === "studio" ? "Architecture Studio" : "AI Blueprint"}
          </h3>
          <p className="text-sm text-muted-foreground">
            {view === "studio"
              ? "Drag components in, wire dependencies, and watch cost and tradeoffs update live."
              : "The original diagram generated by the AI architect."}
          </p>
        </div>
        <div className="inline-flex items-center rounded-lg border border-border bg-muted/50 p-0.5">
          <ViewToggle active={view === "studio"} onClick={() => setView("studio")} icon={PenLine} label="Studio" />
          <ViewToggle active={view === "blueprint"} onClick={() => setView("blueprint")} icon={GitBranch} label="Blueprint" />
        </div>
      </div>

      {view === "studio" ? (
        <ArchitectureCanvas graph={graph} />
      ) : (
        <Card>
          <CardContent className="pt-6">
            {diagram ? <Mermaid chart={diagram} /> : <p className="text-muted-foreground">No diagram generated.</p>}
          </CardContent>
        </Card>
      )}
    </div>
  );
}

function ViewToggle({
  active,
  onClick,
  icon: Icon,
  label,
}: {
  active: boolean;
  onClick: () => void;
  icon: typeof PenLine;
  label: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-medium transition-colors ${
        active ? "bg-card text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"
      }`}
    >
      <Icon className="h-3.5 w-3.5" />
      {label}
    </button>
  );
}

export function ArchitectureViewer({ architecture, isDetail }: ArchitectureViewerProps) {
  return (
    <div className="space-y-6">
      <Tabs defaultValue="diagram" className="w-full">
        <TabsList className="flex flex-wrap h-auto gap-2 bg-muted/50 p-2 justify-start">
          <TabsTrigger value="diagram">Diagram</TabsTrigger>
          <TabsTrigger value="terraform">Terraform</TabsTrigger>
          <TabsTrigger value="cost">Cost Estimate</TabsTrigger>
          <TabsTrigger value="security">Security</TabsTrigger>
          <TabsTrigger value="ha">High Availability</TabsTrigger>
          <TabsTrigger value="database">Database</TabsTrigger>
          <TabsTrigger value="k8s">Kubernetes</TabsTrigger>
          <TabsTrigger value="cicd">CI/CD</TabsTrigger>
          <TabsTrigger value="monitoring">Monitoring</TabsTrigger>
          <TabsTrigger value="dr">Disaster Recovery</TabsTrigger>
        </TabsList>

        <div className="mt-6">
          <TabsContent value="diagram" className="m-0">
            <DiagramTab diagram={architecture.diagram} />
          </TabsContent>

          <TabsContent value="terraform" className="m-0">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between">
                <div>
                  <CardTitle>Terraform Infrastructure</CardTitle>
                  <CardDescription>Infrastructure as Code configuration.</CardDescription>
                </div>
                {isDetail && architecture.id && (
                  <Button variant="outline" size="sm" asChild>
                    <a href={`/api/architectures/${architecture.id}/terraform`} download={`architecture-${architecture.id}.tf`}>
                      <Download className="mr-2 h-4 w-4" />
                      Download .tf
                    </a>
                  </Button>
                )}
              </CardHeader>
              <CardContent>
                {architecture.terraform ? (
                  <CodeBlock code={architecture.terraform} language="hcl" />
                ) : (
                  <p className="text-muted-foreground">No Terraform code generated.</p>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="cost" className="m-0">
            <Card>
              <CardHeader>
                <CardTitle>Cost Estimate</CardTitle>
                <CardDescription>Estimated monthly AWS infrastructure costs.</CardDescription>
              </CardHeader>
              <CardContent>
                <TextSection value={architecture.costEstimate} emptyLabel="No cost estimate generated." />
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="security" className="m-0">
            <Card>
              <CardHeader>
                <CardTitle>Security Recommendations</CardTitle>
                <CardDescription>IAM, network security, and compliance.</CardDescription>
              </CardHeader>
              <CardContent>
                <TextSection value={architecture.securityRecommendations} emptyLabel="No security recommendations generated." />
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="ha" className="m-0">
            <Card>
              <CardHeader>
                <CardTitle>High Availability Plan</CardTitle>
                <CardDescription>Fault tolerance and multi-AZ/Region strategies.</CardDescription>
              </CardHeader>
              <CardContent>
                <TextSection value={architecture.highAvailabilityPlan} emptyLabel="No high availability plan generated." />
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="database" className="m-0">
            <Card>
              <CardHeader>
                <CardTitle>Database Recommendation</CardTitle>
                <CardDescription>Data storage, caching, and persistence choices.</CardDescription>
              </CardHeader>
              <CardContent>
                <TextSection value={architecture.databaseRecommendation} emptyLabel="No database recommendation generated." />
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="k8s" className="m-0">
            <Card>
              <CardHeader>
                <CardTitle>Kubernetes Deployment</CardTitle>
                <CardDescription>EKS configuration and workload manifests.</CardDescription>
              </CardHeader>
              <CardContent>
                {architecture.kubernetesDeployment ? (
                  <CodeBlock code={architecture.kubernetesDeployment} language="yaml" />
                ) : (
                  <p className="text-muted-foreground">No Kubernetes deployment generated.</p>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="cicd" className="m-0">
            <Card>
              <CardHeader>
                <CardTitle>CI/CD Pipeline</CardTitle>
                <CardDescription>GitHub Actions or GitLab CI workflows.</CardDescription>
              </CardHeader>
              <CardContent>
                {architecture.cicdPipeline ? (
                  <CodeBlock code={architecture.cicdPipeline} language="yaml" />
                ) : (
                  <p className="text-muted-foreground">No CI/CD pipeline generated.</p>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="monitoring" className="m-0">
            <Card>
              <CardHeader>
                <CardTitle>Monitoring Setup</CardTitle>
                <CardDescription>Observability, logging, and alerting strategy.</CardDescription>
              </CardHeader>
              <CardContent>
                <TextSection value={architecture.monitoringSetup} emptyLabel="No monitoring setup generated." />
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="dr" className="m-0">
            <Card>
              <CardHeader>
                <CardTitle>Disaster Recovery Plan</CardTitle>
                <CardDescription>RTO/RPO targets, backup strategies, and failover process.</CardDescription>
              </CardHeader>
              <CardContent>
                <TextSection value={architecture.disasterRecovery} emptyLabel="No disaster recovery plan generated." />
              </CardContent>
            </Card>
          </TabsContent>
        </div>
      </Tabs>
    </div>
  );
}
