import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import {
  getGetArchitectureQueryKey,
  getListVersionsQueryKey,
  getListAuditLogsQueryKey,
} from "@workspace/api-client-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Mermaid } from "./mermaid";
import { CodeBlock } from "./code-block";
import { ArchitectureCanvas, useArchitectureGraph } from "./studio/architecture-canvas";
import { ThreatModelView } from "./threat-model-view";
import { VersionHistory } from "./version-history";
import { ActivityTimeline } from "./activity-timeline";
import { Button } from "@/components/ui/button";
import { providerMeta, type CloudProvider } from "@/lib/cloud-providers";
import { streamJsonEvents } from "@/lib/sse-stream";
import { useToast } from "@/hooks/use-toast";
import { Download, PenLine, GitBranch, RefreshCcw, Loader2, History, Activity } from "lucide-react";

interface ArchitectureData {
  id?: number;
  title?: string;
  provider?: string;
  diagram?: string;
  terraform?: string;
  costEstimate?: string;
  securityRecommendations?: string;
  highAvailabilityPlan?: string;
  databaseRecommendation?: string;
  kubernetesDeployment?: string;
  cicdPipeline?: string;
  monitoringSetup?: string;
  disasterRecovery?: string;
  threatModel?: string;
}

interface ArchitectureViewerProps {
  architecture: ArchitectureData;
  isDetail?: boolean;
}

function TextSection({ value, emptyLabel }: { value?: string; emptyLabel: string }) {
  if (!value || !value.trim()) {
    return <p className="text-sm text-muted-foreground">{emptyLabel}</p>;
  }
  return <div className="whitespace-pre-wrap font-mono text-sm leading-relaxed">{value}</div>;
}

/**
 * The diagram tab offers two views of the same design: an interactive Studio
 * (drag, connect, and cost/tradeoff insights) and the AI's original blueprint.
 */
function DiagramTab({
  diagram,
  provider,
  actions,
}: {
  diagram?: string;
  provider: CloudProvider;
  actions?: React.ReactNode;
}) {
  const [view, setView] = useState<"studio" | "blueprint">("studio");
  // Own the graph here so edits survive switching between Studio and Blueprint.
  const graph = useArchitectureGraph(diagram, provider);

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h3 className="text-base font-semibold text-foreground">
            {view === "studio" ? "Architecture Studio" : "AI Blueprint"}
          </h3>
          <p className="text-sm text-muted-foreground">
            {view === "studio"
              ? "Drag components in, wire dependencies, and watch cost and tradeoffs update live."
              : "The original diagram generated by the AI architect."}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {actions}
          <div className="inline-flex items-center rounded-lg border border-border bg-muted/50 p-0.5">
            <ViewToggle active={view === "studio"} onClick={() => setView("studio")} icon={PenLine} label="Studio" />
            <ViewToggle active={view === "blueprint"} onClick={() => setView("blueprint")} icon={GitBranch} label="Blueprint" />
          </div>
        </div>
      </div>

      {view === "studio" ? (
        <ArchitectureCanvas graph={graph} provider={provider} />
      ) : (
        <Card>
          <CardContent className="pt-6">
            {diagram ? <Mermaid chart={diagram} /> : <p className="text-muted-foreground">No diagram generated.</p>}
          </CardContent>
        </Card>
      )}
    </div>
  );
}

function ViewToggle({
  active,
  onClick,
  icon: Icon,
  label,
}: {
  active: boolean;
  onClick: () => void;
  icon: typeof PenLine;
  label: string;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-medium transition-colors ${
        active ? "bg-card text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"
      }`}
    >
      <Icon className="h-3.5 w-3.5" />
      {label}
    </button>
  );
}

export function ArchitectureViewer({ architecture, isDetail }: ArchitectureViewerProps) {
  const provider = providerMeta(architecture.provider);
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const [regenerating, setRegenerating] = useState<string | null>(null);
  const canRegen = Boolean(isDetail && architecture.id);

  const regenerate = async (section: string) => {
    if (!architecture.id || regenerating) return;
    setRegenerating(section);
    try {
      await streamJsonEvents<any>(
        `/api/architectures/${architecture.id}/regenerate-section`,
        { section },
        {
          onChunk: () => {},
          onDone: (result) => {
            if (result?.architecture) {
              queryClient.setQueryData(getGetArchitectureQueryKey(architecture.id!), result.architecture);
            }
            queryClient.invalidateQueries({ queryKey: getListVersionsQueryKey(architecture.id!) });
            queryClient.invalidateQueries({ queryKey: getListAuditLogsQueryKey() });
            toast({ title: "Section regenerated", description: `The ${section} section was updated. The previous state is in History.` });
          },
          onError: (error) => toast({ title: "Regeneration failed", description: error, variant: "destructive" }),
        },
      );
    } catch {
      toast({ title: "Regeneration failed", description: "Could not reach the generation service.", variant: "destructive" });
    } finally {
      setRegenerating(null);
    }
  };

  const regenButton = (section: string) =>
    canRegen ? (
      <Button
        variant="outline"
        size="sm"
        className="gap-1.5"
        disabled={regenerating !== null}
        onClick={() => regenerate(section)}
      >
        {regenerating === section ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RefreshCcw className="h-3.5 w-3.5" />}
        {regenerating === section ? "Regenerating…" : "Regenerate"}
      </Button>
    ) : null;

  return (
    <div className="space-y-6">
      <Tabs defaultValue="diagram" className="w-full">
        <TabsList className="flex flex-wrap h-auto gap-2 bg-muted/50 p-2 justify-start">
          <TabsTrigger value="diagram">Diagram</TabsTrigger>
          <TabsTrigger value="terraform">Terraform</TabsTrigger>
          <TabsTrigger value="cost">Cost Estimate</TabsTrigger>
          <TabsTrigger value="security">Security</TabsTrigger>
          <TabsTrigger value="threat-model">Threat Model</TabsTrigger>
          <TabsTrigger value="ha">High Availability</TabsTrigger>
          <TabsTrigger value="database">Database</TabsTrigger>
          <TabsTrigger value="k8s">Kubernetes</TabsTrigger>
          <TabsTrigger value="cicd">CI/CD</TabsTrigger>
          <TabsTrigger value="monitoring">Monitoring</TabsTrigger>
          <TabsTrigger value="dr">Disaster Recovery</TabsTrigger>
          {isDetail && (
            <>
              <TabsTrigger value="history" className="gap-1.5">
                <History className="h-3.5 w-3.5" /> History
              </TabsTrigger>
              <TabsTrigger value="activity" className="gap-1.5">
                <Activity className="h-3.5 w-3.5" /> Activity
              </TabsTrigger>
            </>
          )}
        </TabsList>

        <div className="mt-6">
          <TabsContent value="diagram" className="m-0">
            <DiagramTab diagram={architecture.diagram} provider={provider.id} actions={regenButton("diagram")} />
          </TabsContent>

          <TabsContent value="terraform" className="m-0">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between">
                <div>
                  <CardTitle>Terraform Infrastructure</CardTitle>
                  <CardDescription>Infrastructure as Code configuration.</CardDescription>
                </div>
                <div className="flex items-center gap-2">
                  {regenButton("terraform")}
                  {isDetail && architecture.id && (
                    <Button variant="outline" size="sm" asChild>
                      <a href={`/api/architectures/${architecture.id}/terraform`} download={`architecture-${architecture.id}.tf`}>
                        <Download className="mr-2 h-4 w-4" />
                        Download .tf
                      </a>
                    </Button>
                  )}
                </div>
              </CardHeader>
              <CardContent>
                {architecture.terraform ? (
                  <CodeBlock code={architecture.terraform} language="hcl" />
                ) : (
                  <p className="text-muted-foreground">No Terraform code generated.</p>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="cost" className="m-0">
            <Card>
              <CardHeader className="flex flex-row items-start justify-between gap-3 space-y-0">
                <div className="space-y-1.5">
                  <CardTitle>Cost Estimate</CardTitle>
                  <CardDescription>Estimated monthly {provider.name} infrastructure costs.</CardDescription>
                </div>
                {regenButton("costEstimate")}
              </CardHeader>
              <CardContent>
                <TextSection value={architecture.costEstimate} emptyLabel="No cost estimate generated." />
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="security" className="m-0">
            <Card>
              <CardHeader className="flex flex-row items-start justify-between gap-3 space-y-0">
                <div className="space-y-1.5">
                  <CardTitle>Security Recommendations</CardTitle>
                  <CardDescription>IAM, network security, and compliance.</CardDescription>
                </div>
                {regenButton("securityRecommendations")}
              </CardHeader>
              <CardContent>
                <TextSection value={architecture.securityRecommendations} emptyLabel="No security recommendations generated." />
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="threat-model" className="m-0">
            <div className="mb-4 flex items-start justify-between gap-3">
              <div>
                <h3 className="text-base font-semibold text-foreground">Threat Model</h3>
                <p className="text-sm text-muted-foreground">
                  STRIDE analysis with mitigations mapped to {provider.name} security services.
                </p>
              </div>
              {regenButton("threatModel")}
            </div>
            <ThreatModelView threatModel={architecture.threatModel} />
          </TabsContent>

          <TabsContent value="ha" className="m-0">
            <Card>
              <CardHeader className="flex flex-row items-start justify-between gap-3 space-y-0">
                <div className="space-y-1.5">
                  <CardTitle>High Availability Plan</CardTitle>
                  <CardDescription>Fault tolerance and multi-AZ/Region strategies.</CardDescription>
                </div>
                {regenButton("highAvailabilityPlan")}
              </CardHeader>
              <CardContent>
                <TextSection value={architecture.highAvailabilityPlan} emptyLabel="No high availability plan generated." />
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="database" className="m-0">
            <Card>
              <CardHeader className="flex flex-row items-start justify-between gap-3 space-y-0">
                <div className="space-y-1.5">
                  <CardTitle>Database Recommendation</CardTitle>
                  <CardDescription>Data storage, caching, and persistence choices.</CardDescription>
                </div>
                {regenButton("databaseRecommendation")}
              </CardHeader>
              <CardContent>
                <TextSection value={architecture.databaseRecommendation} emptyLabel="No database recommendation generated." />
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="k8s" className="m-0">
            <Card>
              <CardHeader className="flex flex-row items-start justify-between gap-3 space-y-0">
                <div className="space-y-1.5">
                  <CardTitle>Kubernetes Deployment</CardTitle>
                  <CardDescription>Managed Kubernetes configuration and workload manifests.</CardDescription>
                </div>
                {regenButton("kubernetesDeployment")}
              </CardHeader>
              <CardContent>
                {architecture.kubernetesDeployment ? (
                  <CodeBlock code={architecture.kubernetesDeployment} language="yaml" />
                ) : (
                  <p className="text-muted-foreground">No Kubernetes deployment generated.</p>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="cicd" className="m-0">
            <Card>
              <CardHeader className="flex flex-row items-start justify-between gap-3 space-y-0">
                <div className="space-y-1.5">
                  <CardTitle>CI/CD Pipeline</CardTitle>
                  <CardDescription>GitHub Actions or GitLab CI workflows.</CardDescription>
                </div>
                {regenButton("cicdPipeline")}
              </CardHeader>
              <CardContent>
                {architecture.cicdPipeline ? (
                  <CodeBlock code={architecture.cicdPipeline} language="yaml" />
                ) : (
                  <p className="text-muted-foreground">No CI/CD pipeline generated.</p>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="monitoring" className="m-0">
            <Card>
              <CardHeader className="flex flex-row items-start justify-between gap-3 space-y-0">
                <div className="space-y-1.5">
                  <CardTitle>Monitoring Setup</CardTitle>
                  <CardDescription>Observability, logging, and alerting strategy.</CardDescription>
                </div>
                {regenButton("monitoringSetup")}
              </CardHeader>
              <CardContent>
                <TextSection value={architecture.monitoringSetup} emptyLabel="No monitoring setup generated." />
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="dr" className="m-0">
            <Card>
              <CardHeader className="flex flex-row items-start justify-between gap-3 space-y-0">
                <div className="space-y-1.5">
                  <CardTitle>Disaster Recovery Plan</CardTitle>
                  <CardDescription>RTO/RPO targets, backup strategies, and failover process.</CardDescription>
                </div>
                {regenButton("disasterRecovery")}
              </CardHeader>
              <CardContent>
                <TextSection value={architecture.disasterRecovery} emptyLabel="No disaster recovery plan generated." />
              </CardContent>
            </Card>
          </TabsContent>

          {isDetail && architecture.id && (
            <>
              <TabsContent value="history" className="m-0">
                <div className="mb-4">
                  <h3 className="text-base font-semibold text-foreground">Version History</h3>
                  <p className="text-sm text-muted-foreground">
                    Every meaningful change is captured. Compare snapshots side by side or roll back.
                  </p>
                </div>
                <VersionHistory
                  architectureId={architecture.id}
                  current={{
                    title: architecture.title,
                    requirements: (architecture as Record<string, any>).requirements,
                    provider: architecture.provider,
                    diagram: architecture.diagram,
                    terraform: architecture.terraform,
                    costEstimate: architecture.costEstimate,
                    securityRecommendations: architecture.securityRecommendations,
                    highAvailabilityPlan: architecture.highAvailabilityPlan,
                    databaseRecommendation: architecture.databaseRecommendation,
                    kubernetesDeployment: architecture.kubernetesDeployment,
                    cicdPipeline: architecture.cicdPipeline,
                    monitoringSetup: architecture.monitoringSetup,
                    disasterRecovery: architecture.disasterRecovery,
                    threatModel: architecture.threatModel,
                  }}
                />
              </TabsContent>

              <TabsContent value="activity" className="m-0">
                <div className="mb-4">
                  <h3 className="text-base font-semibold text-foreground">Activity</h3>
                  <p className="text-sm text-muted-foreground">
                    A read-only trail of everything that happened to this architecture.
                  </p>
                </div>
                <ActivityTimeline architectureId={architecture.id} />
              </TabsContent>
            </>
          )}
        </div>
      </Tabs>
    </div>
  );
}
